sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script: "./travis-build.sh"
env:
  global:
  - secure: KyWzkNdQTMPx8Ru3Xpy/jER7DblDcpbvvzZTsY0vTzr1XET/QASmXefRnasth+XV6jGKhGnhRW2yjYDOJxfEq49Ni7WizfHJWZT7WgiVAYZN8yIVMzvjr3FcxMGjLOovUuZQ9brGtFYTzf6tKeawb16zNDLxWDQiHm0MPMepyGMuefbUWeOvjHIq2AKDPFw4EUXQmi9oxP0upp1kPMFZYc8wloI+ET85LCaf6etv5ls1aH7KwqgDm/nqGBs8qSOUoR4xtrAzfIigz7cGV58BlHj8tskN00/7oDdf7dy6R8AyL5zZsIN38FFM66aOGvV+7dYT5NWF1hHxM544NvuuCJOeUFyJDJOj5JaT0lFJv1tFoG3Gr3ud0FQVv8/VAEXoayFSgwMSt62SXMIHore3M6ET2PwhsVomaev9XgF4noQZ7ZVvuwUXSzSpRggz4PZMIJPUMmu7+UC9SOCdS3zEhWKGNz0094MZmwaQYB4EjjgC1UuXpEY3tmsfT3hPIQ6DtYEgeY/wLI6N9RgqjwQbCWzoJUE3P0wcuLs3gdP+cqjFKCoUQrlgPEtkt0uhJPNa/o3fpP05A9xuEsaxT2FDiS/g/vvFvk37cPsvoxpSfF2OBnQOLyWhNig/8RbFAb0PYiQGtDd7XtOOH0etZWVyOiZUHdajc1rgNp0xiajgKL4=
  - secure: IoWdNZ+f3WO4QvcVHr+jLmQ6Se1TUmBS2vx5Uzmgr+xnlP08eE9Q+5+ZqOCwHdI9+ItCQhHDiVkShJXzElCIUheo05vtLqSn5/1KDOhezxxs7XdoBX+BIC1wSoTDtumIvk8yl/6cErt4+j9QhiZyIpmJdKy76CLtF81ecvTGlP1J6BFb3pZOV0decEGOtAxiluFQYkerxn+Og6TSI2/COqndijVjfl3DU1oPu1mt7dw2CfuSBRF+Jl+JYA1g27IDJcPUeN7aI2/aKSYSmxpHCYlLsirS046d9/jajP2AK51xtqBdaHQnoTsUZGWbZTHvAZqtnwdnAZ7E96o8z0wFgCedZqk1w1BuXHx4C8rnAPWEUbcbhFnoG8HdtGTVPiSuXMzmagDo2cdoP/Xw6Yn18PTBsXUu3+AeT6hsgrZs94iMyCI4olskRBcs9iFHawEeWOVrMC/bTWhYb9OslKKRuqAuLmJzV65lOLXxrys7SXfmSO88LBTIJcwu6qBouFXVLTQ6znVGOEihOvoNZ43/hIAh6cOlNlk5qjFAAJ035OBffVryD9/f0NaK/eVkWgAqyY1+ww4s0ky7nuTkleineGJ8lWW7v23W9hDVX80z7fp5KLwU3z0ibz1r/6rwXJ0h9YMqJffrinHxIdUaVTAR8Zk4VlJ6ekCEshPfTQMZF1U=
